### ISSUE TITLE
Characters, animals and vehicles need scripting

### ISSUE THREAD

**Issue by RaphaelGodlis** [RaphaelGodlis/Sensand#34]
The characters and vehicles have been animated, but they need scripted movement patterns. The movement speeds will also need to be adjusted. The animals will need this to be done as well when they're ready. Though they can be done on a separate branch.

**Comment by MathewMann** [comment]
Use this tutorial if stuck.
http://www.unrealenginetutorials.com/make-ai-character-to-move-over-a-defined-path-ai-character-simple-patrol/
